export const initialState = {
  user: JSON.parse(localStorage.getItem("user")) || null,
  // user: null,
  allUsers: null,
  allSongs: null,
  allArtists: null,
  allAlbums: null,
  filterTerm: "all",
  artistfilter: null,
  languageFilter: null,
  albumFilter: null,
  alertTYpe: null,
  isSongPlaying: false,
  songIndex: 0,
  favoriteSongs: [],
};
